apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/zakyaakram/CloudDevOpsProject.git
    targetRevision: master
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: ivolve

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
