name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker Image
      run: |
        docker build -t zakya-devops-app ./app

    - name: Tag Docker Image
      run: |
        docker tag zakya-devops-app:latest 306767070773.dkr.ecr.eu-north-1.amazonaws.com/zakya-devops-app:latest

    - name: Push Docker Image to ECR
      run: |
        docker push 306767070773.dkr.ecr.eu-north-1.amazonaws.com/zakya-devops-app:latest
